In [1]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\Raunak\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\Raunak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Raunak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Raunak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\Raunak\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import numpy as np
import pandas as pd

In [3]:
s = pd.Series([1,2,4,6,7])

In [4]:
s

0    1
1    2
2    4
3    6
4    7
dtype: int64

In [5]:
dates = pd.date_range('20210609', periods=5)

In [6]:
dates

DatetimeIndex(['2021-06-09', '2021-06-10', '2021-06-11', '2021-06-12',
               '2021-06-13'],
              dtype='datetime64[us]', freq='D')

In [7]:
df = pd.DataFrame(np.random.randn(5, 4), index = dates, columns=list('ABCD'))

In [8]:
df

                   A         B         C         D
2021-06-09  0.033965 -0.704469  1.012977 -0.484502
2021-06-10 -0.892442  0.698208  0.802866 -0.286135
2021-06-11  0.137866 -1.625260 -1.200228 -0.376471
2021-06-12  0.957034 -0.475251 -0.383165  1.530838
2021-06-13  0.071538  2.406718 -1.289253  0.077562

In [9]:
df.dtypes

A    float64
B    float64
C    float64
D    float64
dtype: object

In [10]:
df.head()

                   A         B         C         D
2021-06-09  0.033965 -0.704469  1.012977 -0.484502
2021-06-10 -0.892442  0.698208  0.802866 -0.286135
2021-06-11  0.137866 -1.625260 -1.200228 -0.376471
2021-06-12  0.957034 -0.475251 -0.383165  1.530838
2021-06-13  0.071538  2.406718 -1.289253  0.077562

In [11]:
df.head(2)

                   A         B         C         D
2021-06-09  0.033965 -0.704469  1.012977 -0.484502
2021-06-10 -0.892442  0.698208  0.802866 -0.286135

In [12]:
df.tail(2)

                   A         B         C         D
2021-06-12  0.957034 -0.475251 -0.383165  1.530838
2021-06-13  0.071538  2.406718 -1.289253  0.077562

In [13]:
df.index

DatetimeIndex(['2021-06-09', '2021-06-10', '2021-06-11', '2021-06-12',
               '2021-06-13'],
              dtype='datetime64[us]', freq='D')

In [14]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='str')

In [15]:
df.to_numpy()

array([[ 0.03396483, -0.70446926,  1.01297674, -0.4845024 ],
       [-0.89244151,  0.69820847,  0.80286601, -0.286135  ],
       [ 0.1378656 , -1.62526015, -1.2002276 , -0.37647077],
       [ 0.95703449, -0.47525093, -0.38316498,  1.53083827],
       [ 0.07153816,  2.40671819, -1.28925266,  0.07756216]])

In [16]:
df.describe()

              A         B         C         D
count  5.000000  5.000000  5.000000  5.000000
mean   0.061592  0.059989 -0.211360  0.092258
std    0.655492  1.551242  1.083615  0.831455
min   -0.892442 -1.625260 -1.289253 -0.484502
25%    0.033965 -0.704469 -1.200228 -0.376471
50%    0.071538 -0.475251 -0.383165 -0.286135
75%    0.137866  0.698208  0.802866  0.077562
max    0.957034  2.406718  1.012977  1.530838

In [17]:
df.T

   2021-06-09  2021-06-10  2021-06-11  2021-06-12  2021-06-13
A    0.033965   -0.892442    0.137866    0.957034    0.071538
B   -0.704469    0.698208   -1.625260   -0.475251    2.406718
C    1.012977    0.802866   -1.200228   -0.383165   -1.289253
D   -0.484502   -0.286135   -0.376471    1.530838    0.077562

In [18]:
df.sort_index(axis = 1, ascending = False)

                   D         C         B         A
2021-06-09 -0.484502  1.012977 -0.704469  0.033965
2021-06-10 -0.286135  0.802866  0.698208 -0.892442
2021-06-11 -0.376471 -1.200228 -1.625260  0.137866
2021-06-12  1.530838 -0.383165 -0.475251  0.957034
2021-06-13  0.077562 -1.289253  2.406718  0.071538

In [19]:
df.sort_values(by = 'B')

                   A         B         C         D
2021-06-11  0.137866 -1.625260 -1.200228 -0.376471
2021-06-09  0.033965 -0.704469  1.012977 -0.484502
2021-06-12  0.957034 -0.475251 -0.383165  1.530838
2021-06-10 -0.892442  0.698208  0.802866 -0.286135
2021-06-13  0.071538  2.406718 -1.289253  0.077562

In [20]:
df['C']

2021-06-09    1.012977
2021-06-10    0.802866
2021-06-11   -1.200228
2021-06-12   -0.383165
2021-06-13   -1.289253
Freq: D, Name: C, dtype: float64

In [21]:
df[0:3]

                   A         B         C         D
2021-06-09  0.033965 -0.704469  1.012977 -0.484502
2021-06-10 -0.892442  0.698208  0.802866 -0.286135
2021-06-11  0.137866 -1.625260 -1.200228 -0.376471

In [22]:
df['20210610':'20210611']

                   A         B         C         D
2021-06-10 -0.892442  0.698208  0.802866 -0.286135
2021-06-11  0.137866 -1.625260 -1.200228 -0.376471

In [23]:
df.loc[dates[0]]

A    0.033965
B   -0.704469
C    1.012977
D   -0.484502
Name: 2021-06-09 00:00:00, dtype: float64

In [24]:
df.loc[:, ['A', 'B']]

                   A         B
2021-06-09  0.033965 -0.704469
2021-06-10 -0.892442  0.698208
2021-06-11  0.137866 -1.625260
2021-06-12  0.957034 -0.475251
2021-06-13  0.071538  2.406718

In [25]:
df.loc['20210609':'20210611',['A', 'C']]

                   A         C
2021-06-09  0.033965  1.012977
2021-06-10 -0.892442  0.802866
2021-06-11  0.137866 -1.200228

In [26]:
df.iloc[3]

A    0.957034
B   -0.475251
C   -0.383165
D    1.530838
Name: 2021-06-12 00:00:00, dtype: float64

In [27]:
df.iloc[2:4,0:3]

                   A         B         C
2021-06-11  0.137866 -1.625260 -1.200228
2021-06-12  0.957034 -0.475251 -0.383165

Boolean Indexing

In [28]:
df[df.A > 0]

                   A         B         C         D
2021-06-09  0.033965 -0.704469  1.012977 -0.484502
2021-06-11  0.137866 -1.625260 -1.200228 -0.376471
2021-06-12  0.957034 -0.475251 -0.383165  1.530838
2021-06-13  0.071538  2.406718 -1.289253  0.077562

In [29]:
df.A

2021-06-09    0.033965
2021-06-10   -0.892442
2021-06-11    0.137866
2021-06-12    0.957034
2021-06-13    0.071538
Freq: D, Name: A, dtype: float64

In [30]:
df[df.A < 0]

                   A         B         C         D
2021-06-10 -0.892442  0.698208  0.802866 -0.286135

In [31]:
df.isnull()

                A      B      C      D
2021-06-09  False  False  False  False
2021-06-10  False  False  False  False
2021-06-11  False  False  False  False
2021-06-12  False  False  False  False
2021-06-13  False  False  False  False

In [32]:
df.isna()

                A      B      C      D
2021-06-09  False  False  False  False
2021-06-10  False  False  False  False
2021-06-11  False  False  False  False
2021-06-12  False  False  False  False
2021-06-13  False  False  False  False

In [33]:
df.mean()

A    0.061592
B    0.059989
C   -0.211360
D    0.092258
dtype: float64

In [34]:
df.median()

A    0.071538
B   -0.475251
C   -0.383165
D   -0.286135
dtype: float64

In [35]:
df.to_json('new.json')

In [42]:
ls

 Volume in drive C has no label.
 Volume Serial Number is EEB2-37E3

 Directory of C:\Users\Admin\Documents\GettingStartedWithML\18_pandas

09-06-2021  00:57    <DIR>          .
09-06-2021  00:57    <DIR>          ..
09-06-2021  00:36    <DIR>          .ipynb_checkpoints
09-06-2021  00:57               612 new.json
09-06-2021  00:56            45,916 Pandas_Walkthrough.ipynb
               2 File(s)         46,528 bytes
               3 Dir(s)  213,180,919,808 bytes free

In [43]:
df.to_csv('newcsv.csv')

In [44]:
ls

 Volume in drive C has no label.
 Volume Serial Number is EEB2-37E3

 Directory of C:\Users\Admin\Documents\GettingStartedWithML\18_pandas

09-06-2021  00:58    <DIR>          .
09-06-2021  00:58    <DIR>          ..
09-06-2021  00:36    <DIR>          .ipynb_checkpoints
09-06-2021  00:57               612 new.json
09-06-2021  00:58               466 newcsv.csv
09-06-2021  00:56            45,916 Pandas_Walkthrough.ipynb
               3 File(s)         46,994 bytes
               3 Dir(s)  213,167,484,928 bytes free

In [45]:
csv_data = pd.read_csv('newcsv.csv')

In [46]:
csv_data

   Unnamed: 0         A         B         C         D
0  2021-06-09 -0.550111  1.570150 -2.057431  0.058547
1  2021-06-10 -0.229350  1.626667 -1.697047  0.066035
2  2021-06-11 -2.082050 -0.030690  0.551818  0.084764
3  2021-06-12 -2.021212 -1.295692 -0.250714  0.624834
4  2021-06-13 -0.549771  0.551846 -0.103707  1.117387